Update wercker.yml

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -1,29 +1,24 @@
-# This references a standard debian container from the
-# Docker Hub https://registry.hub.docker.com/_/debian/
-# Read more about containers on our dev center
-# http://devcenter.wercker.com/docs/containers/index.html
-box: debian
-# You can also use services such as databases. Read more on our dev center:
-# http://devcenter.wercker.com/docs/services/index.html
-# services:
-    # - postgres
-    # http://devcenter.wercker.com/docs/services/postgresql.html
-
-    # - mongodb
-    # http://devcenter.wercker.com/docs/services/mongodb.html
-
-# This is the build pipeline. Pipelines are the core of wercker
-# Read more about pipelines on our dev center
-# http://devcenter.wercker.com/docs/pipelines/index.html
-build:
-  # The steps that will be executed on build
-  steps:
-    - script:
-        name: TaskHandler
-        code: |
-          sudo apt-get install maven
-          mvn -v
-    - script:
-        name: mvn clean instal
-        code: |
-          mvn clean install
+# Install Java7
+  sudo apt-get update
+  sudo apt-get install python-software-properties curl wget -y
+  sudo add-apt-repository ppa:webupd8team/java -y
+  sudo apt-get update
+  echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
+  echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
+  sudo apt-get install oracle-java7-installer -qq
+  # Install sbt
+  wget http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch//0.12.3/sbt-launch.jar
+  printf 'java -Dsbt.ivy.home=${IVY_CACHE_DIR} -Xmx512M ${SBT_OPTS} -jar `dirname $0`/sbt-launch.jar "$@"' > sbt
+  sudo chmod +x ./sbt
+  sudo mv sbt /usr/share/sbt
+  sudo mv sbt-launch.jar /usr/share/sbt-launch.jar
+  sudo ln -s /usr/share/sbt /usr/bin/sbt
+  sudo ln -s /usr/share/sbt-launch.jar /usr/bin/sbt-launch.jar
+  # Install maven
+  sudo apt-get install maven
+  # Install ant
+  sudo apt-get install ant ant-contrib ivy ivy-doc -y -qq
+  sudo mv sbt /usr/share/sbt
+   # We should have ant and ivy available
+  type ant || { echo "I expected ant to be available. Aborting."; exit 1; }
+  type mvn || { echo "I expected maven to be available. Aborting."; exit 1; }
